// enum UserRole {
//     ADMIN,
//     EXECUTIVE,
//     VOLUNTEER,
//     FANICIAL,
//     COMMUNITY,
// }

// enum ProfileRole {
//     COUPLE,//$30
//     FAMILY_WITH_CHILDREN, //50
//     SINGLE_AND_STUDENT, //$20//$20
//     LIFETIME_FREE, //0
//     DONORS,//$500
//     NEW_ARRIVALS //
// }

export enum UserRole {
    SUPER_ADMIN,
    CAR_RENTAL_ADMIN,
    FANICIAL_COUPLE,//$30
    FANICIAL_FAMILY_WITH_CHILDREN, //50
    FANICIAL_SINGLE_AND_STUDENT, //$20//$20
    FANICIAL_LIFETIME_FREE, //0
    FANICIAL_DONORS,//$500
    FANICIAL_NEW_ARRIVALS,//
    // EXECUTIVE,
    VOLUNTEER,
    // FANICIAL,
    COMMUNITY
}